apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tire: backend
    environment: dev
data:
   MONGO: true
   MONGO_URL: mongodb://mongodb:27017/catalogue
